version: '3.8'
services:
  mongo:
    image: mongo:4.4.4
    container_name: mongo
    ports:
      - 27017:27017
  postgres:
    image: postgres:13.2
    container_name: postgres
    volumes: 
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

