version: '3.8'
services:
  mongodb:
    image: mongo:3.6.20
    container_name: mongo 
    ports:
      - '27017:27017'
    restart: always
  postgres:
    image: postgres:11
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432