version: '3.8'
services:
  firmco-app:
    build:
      dockerfile: dockerfile
      context: .
    image: erp-web-api
    container_name: erp-web-api
    restart: always
    depends_on:
      - firmco-mongo
      - firmco-postgres
    environment:
      - DS_URL=jdbc:postgresql://firmco-postgres:45432/firmco
      - DS_USERNAME=firmco
      - DS_PASSWORD=123456
    ports:
      - 8080:8080
      - 8000:8000
  firmco-mongo:
    image: mongo:4.4.4
    container_name: eap-mongo
    ports:
      - 47017:27017
  firmco-postgres:
    image: postgres:13.2
    container_name: eap-postgres
    volumes:
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 45432:5432
