server:
  port: 8080
  servlet:
    context-path: /

spring:
  profiles:
    active: @active.profiles@
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: master
---
server:
  port: 80
  servlet:
    context-path: /

spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:45432/firmco
    username: firmco
    password: 123456
    initialization-mode: always
    initialize: true
    continue-on-error: true
---
spring:
  profiles: stage
  datasource:
    url: ${DS_URL}
    username: ${DS_USERNAME}
    password: ${DS_PASSWORD}
    initialization-mode: always
    initialize: true
    continue-on-error: true
---
spring:
  profiles: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/firmco
    username: firmco
    password: 123456
    initialization-mode: always
    initialize: true
    continue-on-error: true
